### ISSUE TITLE
"HMAC signature does not match"

### ISSUE THREAD

**Issue by garthoid** [brunocvcunha/coinpayments-java#1]
Using the basic example:
```
CoinPayments api = CoinPayments.builder()
        .publicKey("<publicKey>")
        .privateKey("<privateKey>")
        .client(HttpClients.createDefault()).build();

ResponseWrapper<BasicInfoResponse> accountInfo = api.sendRequest(new CoinPaymentsBasicAccountInfoRequest());
log.info("Account: " + accountInfo.getResult());
```
Where publicKey and Private key are strings loaded from my environment.

The server response is:

`{"error":"HMAC signature does not match","result":[]}`

Using maven to pull down the latest.

Suggestions?

**Comment by garthoid** [comment]
Scratch that. Bad read. My Bad.

**Comment by pste22** [comment]
Hi all,

I am running below curl command as a test the api but it failes with error : 33{"error":"HMAC signature does not match","result":[]}
can someone suggest whats the right HMAC and how i can generate it ?

command  used  :

curl --request POST --url https://www.coinpayments.net/api.php --header 'Content-Type: application/x-www-form-urlencoded' --header 'HMAC:HMAC_GENERATED_AGAINST_MY_PRIVATE_KEY_ONLINE' --data 'version=1&cmd=rates&key=MY_PUBLIC_KEY&format=json'

**Comment by vipulwairagade** [comment]
@garthoid Can you explain the possibilities why we might be getting this error ? I'm doing everything right. I'm doing it in node.js
